class VantaRadio {
  constructor({url,role,getFrequencies,getFrequency,getCallsign,onStatus}){this.url=url;this.role=role;this.getFrequencies=getFrequencies||(()=>[]);this.getFrequency=getFrequency||(()=>null);this.getCallsign=getCallsign||(()=> 'VANTA');this.onStatus=onStatus||(()=>{});this.ws=null;this.stream=null;this.audio=null;this.processor=null;this.ptt=false;this.nextPlayTime=0;}
  status(s){this.onStatus(s)}
  connect(){if(this.ws&&this.ws.readyState<=1)return;this.ws=new WebSocket(this.url);this.ws.binaryType='arraybuffer';this.ws.onopen=()=>{this.ws.send(JSON.stringify({protocol:'VANTA/1',ts:Date.now(),type:'DEV_AUTH',role:this.role,clientName:'vanta-radio'}));setTimeout(()=>this.sync(),120);this.status('RADIO ONLINE')};this.ws.onclose=()=>this.status('RADIO OFFLINE');this.ws.onerror=()=>this.status('RADIO ERROR');this.ws.onmessage=e=>{if(e.data instanceof ArrayBuffer)this.play(e.data)}}
  sync(){if(!this.ws||this.ws.readyState!==WebSocket.OPEN)return;const f=this.getFrequencies().map(Number).filter(Number.isFinite).slice(0,2);if(!f.length){const one=Number(this.getFrequency());if(Number.isFinite(one))f.push(one)}if(this.role==='PILOT'){const c=String(this.getCallsign()||'VANTA').toUpperCase();this.ws.send(JSON.stringify({protocol:'VANTA/1',ts:Date.now(),type:'FREQUENCY_UPDATE',callsign:c,com1ActiveMhz:f[0]??null,com2ActiveMhz:f[1]??null}))}else{const c=String(this.getCallsign()||'VANTA_ATC').toUpperCase();this.ws.send(JSON.stringify({protocol:'VANTA/1',ts:Date.now(),type:'FREQUENCY_UPDATE',callsign:c,com1ActiveMhz:f[0]??null,com2ActiveMhz:null}))}}
  async startPtt(){if(this.ptt)return;this.connect();if(!this.ws||this.ws.readyState!==WebSocket.OPEN){this.status('WAITING FOR NETWORK');return}const frequency=Number(this.getFrequency());const callsign=String(this.getCallsign()||'VANTA').toUpperCase();if(!Number.isFinite(frequency)||frequency<118||frequency>137){this.status('INVALID FREQUENCY');return}this.ws.send(JSON.stringify({protocol:'VANTA/1',ts:Date.now(),type:'PTT_START',callsign,radio:'COM1',frequencyMhz:frequency}));try{if(!this.stream)this.stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(!this.audio)this.audio=new AudioContext({sampleRate:48000});await this.audio.resume();const source=this.audio.createMediaStreamSource(this.stream);this.processor=this.audio.createScriptProcessor(1024,1,1);this.processor.onaudioprocess=e=>{if(!this.ptt||!this.ws||this.ws.readyState!==WebSocket.OPEN)return;const input=e.inputBuffer.getChannelData(0),pcm=new Int16Array(input.length);for(let i=0;i<input.length;i++){const s=Math.max(-1,Math.min(1,input[i]));pcm[i]=s<0?s*32768:s*32767}const packet=new Uint8Array(4+pcm.byteLength);packet.set([86,82,65,49]);packet.set(new Uint8Array(pcm.buffer),4);if(this.ws.bufferedAmount<65536)this.ws.send(packet)};source.connect(this.processor);this.processor.connect(this.audio.destination);this.ptt=true;this.status('TRANSMITTING')}catch(e){this.status('MICROPHONE DENIED');this.stopPtt()}}
  stopPtt(){if(this.ws&&this.ws.readyState===WebSocket.OPEN){const f=Number(this.getFrequency()),c=String(this.getCallsign()||'VANTA').toUpperCase();if(Number.isFinite(f))this.ws.send(JSON.stringify({protocol:'VANTA/1',ts:Date.now(),type:'PTT_STOP',callsign:c,radio:'COM1'}))}this.ptt=false;if(this.processor){this.processor.disconnect();this.processor.onaudioprocess=null;this.processor=null}this.status('RADIO ONLINE')}
  play(packet){if(packet.byteLength<6)return;const b=new Uint8Array(packet);if(b[0]!==86||b[1]!==82||b[2]!==65||b[3]!==49)return;if(!this.audio)this.audio=new AudioContext({sampleRate:48000});this.audio.resume();const pcm=new Int16Array(packet.slice(4)),buffer=this.audio.createBuffer(1,pcm.length,48000),out=buffer.getChannelData(0);for(let i=0;i<pcm.length;i++)out[i]=pcm[i]/32768;const source=this.audio.createBufferSource();source.buffer=buffer;source.connect(this.audio.destination);const now=this.audio.currentTime;this.nextPlayTime=Math.max(this.nextPlayTime,now+0.02);source.start(this.nextPlayTime);this.nextPlayTime+=buffer.duration}
}
window.VantaRadio=VantaRadio;
